name: Build and deploy Zola website
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs: 
  build:
    runs-on: ubuntu-latest
    step:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@v1
        with: zola_version: "0.22.1"

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4